spring:
    datasource:
      driver-class-name: org.apache.calcite.jdbc.Driver
      url: "jdbc:calcite:"
      druid:
        connect-properties:
          lex: MYSQL
          model: |-
            inline:
            {
              "defaultSchema": "db1",
              "schemas": [
                {
                  "factory": "org.apache.calcite.adapter.jdbc.JdbcSchema$Factory",
                  "name": "db1",
                  "operand": {
                    "jdbcDriver": "com.mysql.cj.jdbc.Driver",
                    "jdbcPassword": "test",
                    "jdbcUrl": "jdbc:mysql://localhost:3306/user_service",
                    "jdbcUser": "root"
                  },
                  "type": "custom"
                },
                {
                  "name": "db2",
                  "operand": {
                    "jdbcDriver": "oracle.jdbc.OracleDriver",
                    "jdbcPassword": "test",
                    "jdbcUrl": "jdbc:oracle:thin:@//localhost:1521/test",
                    "jdbcUser": "test"
                  },
                  "type": "custom",
                  "factory": "org.apache.calcite.adapter.jdbc.JdbcSchema$Factory"
                }
              ],
              "version": "1.0"
            }
      type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl